<#
.SYNOPSIS
    ONE-TIME admin setup for network drive deployments.

.DESCRIPTION
    Reads every app from the app registry, collects all requirements.txt files,
    and installs every package directly into the bundled runtime's site-packages.
    After this runs once, ALL users get instant app launches -- no venv creation,
    no pip install, no waiting.

    Run this:
      - Once after placing the release folder on the network drive.
      - Again whenever you add a new app or bump a package version.

    Requires write access to the bundled runtime folder.

.PARAMETER ReleaseDir
    Path to the repository or portable release folder.
    Auto-detected: checks build\Unified-Pipeline-Launcher\ first, then the
    repo root itself (so you can run this directly from a repo on a network drive).

.EXAMPLE
    .\src\scripts\prepare_shared_runtime.ps1
    .\src\scripts\prepare_shared_runtime.ps1 -ReleaseDir "Z:\Unified-Pipeline-Launcher"
#>

param(
    [string]$ReleaseDir = "",
    [switch]$Upgrade
)

$ErrorActionPreference = "Stop"

# Auto-detect the release or repository root
if ($ReleaseDir -eq "") {
    $SourceRoot = Split-Path -Parent $PSScriptRoot
    $ScriptParent = Split-Path -Parent $SourceRoot

    # Option A: built release folder exists alongside repo
    $BuildRelease = Join-Path $SourceRoot "build\Unified-Pipeline-Launcher"
    if (Test-Path (Join-Path $BuildRelease "runtime\python.exe")) {
        $ReleaseDir = $BuildRelease
    }
    # Option B: running directly from the repo root (src\runtime\ is in the repo)
    elseif (Test-Path (Join-Path $ScriptParent "src\runtime\python.exe")) {
        $ReleaseDir = $ScriptParent
    }
    else {
        $ReleaseDir = $ScriptParent   # will fail below with a clear message
    }
}

$ReleaseDir = Resolve-Path $ReleaseDir
$SourceRoot = Join-Path $ReleaseDir "src"
if (-not (Test-Path $SourceRoot)) {
    $SourceRoot = $ReleaseDir
}

Write-Host ""
Write-Host "============================================================"
Write-Host "  Unified Pipeline Launcher -- Shared Runtime Setup"
Write-Host "============================================================"
Write-Host "Release folder : $ReleaseDir"

# Find the bundled Python runtime
$Python = Join-Path $SourceRoot "runtime\python.exe"
if (-not (Test-Path $Python)) {
    Write-Error @"
Bundled runtime not found at: $Python

Run src\scripts\fetch_runtime.ps1 first to download a portable Python runtime,
then re-run this script.
"@
    exit 1
}
Write-Host "Runtime python : $Python"
$PythonVersion = & $Python --version 2>&1
Write-Host "Python version : $PythonVersion"

# Read the app registry
$AppsRoot = Join-Path $SourceRoot "apps"
$AppsJson = Join-Path $AppsRoot "apps.json"
if (-not (Test-Path $AppsJson)) {
    Write-Error "App registry not found: $AppsJson"
    exit 1
}
$Registry = Get-Content $AppsJson -Raw | ConvertFrom-Json

# Collect requirements files
$AllRequirements = @()
$AllWheelhouses  = @()

$LauncherRequirements = Join-Path $SourceRoot "requirements-launcher.txt"
if (Test-Path $LauncherRequirements) {
    $AllRequirements += $LauncherRequirements
    Write-Host "  Found launcher requirements: requirements-launcher.txt"
} else {
    Write-Error "Launcher requirements not found: $LauncherRequirements"
    exit 1
}

foreach ($App in $Registry.applications) {
    if ($App.enabled -eq $false) { continue }

    $AppFolder = Join-Path $AppsRoot $App.folder
    $ReqFile   = Join-Path $AppFolder "requirements.txt"

    if (Test-Path $ReqFile) {
        $AllRequirements += $ReqFile
        Write-Host "  Found requirements: apps\$($App.folder)\requirements.txt"
    } else {
        Write-Host "  (no requirements.txt for $($App.name))"
    }

    $WheelDir = Join-Path $AppFolder "wheelhouse"
    if (Test-Path $WheelDir) {
        $AllWheelhouses += $WheelDir
    }
}

# Merge requirements into a temporary file
$TempReq = [System.IO.Path]::GetTempFileName() + ".txt"
$Lines   = @("# Auto-generated by prepare_shared_runtime.ps1")
foreach ($ReqFile in $AllRequirements) {
    $Lines += "# --- $ReqFile ---"
    $Lines += Get-Content $ReqFile
}
$Lines | Set-Content -Path $TempReq -Encoding UTF8
Write-Host ""
Write-Host "Merged $($AllRequirements.Count) requirements file(s)."

# Upgrade pip
Write-Host "Upgrading pip..."
& $Python -m pip install --upgrade pip --quiet
if ($LASTEXITCODE -ne 0) { Write-Warning "pip upgrade failed (non-fatal, continuing)" }

# Install packages
Write-Host ""
Write-Host "Installing all packages into shared runtime..."
Write-Host "(This may take a few minutes on first run.)"
Write-Host ""

$PipArgs = @("-m", "pip", "install", "--no-warn-script-location")
if ($Upgrade) {
    $PipArgs += "--upgrade"
}

if ($AllWheelhouses.Count -gt 0) {
    Write-Host "Using offline wheelhouse(s) for faster install."
    $PipArgs += "--prefer-binary"
    foreach ($WheelDir in $AllWheelhouses) {
        $PipArgs += "--find-links"
        $PipArgs += $WheelDir
    }
}

$PipArgs += "-r"
$PipArgs += $TempReq

& $Python @PipArgs
$ExitCode = $LASTEXITCODE

Remove-Item $TempReq -Force -ErrorAction SilentlyContinue

if ($ExitCode -ne 0) {
    Write-Error "Package installation failed (exit code $ExitCode)."
    exit $ExitCode
}

# Verify imports
Write-Host ""
Write-Host "Verifying launcher and Streamlit imports..."
& $Python -c "from PySide6.QtWidgets import QApplication; import streamlit; print('  PySide6 and streamlit OK')"
if ($LASTEXITCODE -ne 0) {
    Write-Error "PySide6 or Streamlit import failed after installation."
    exit 1
}

# Write the runtime marker
$Marker = @{
    prepared_at   = (Get-Date -Format "o")
    python        = $PythonVersion.ToString()
    release_dir   = $ReleaseDir.ToString()
    requirements  = $AllRequirements
} | ConvertTo-Json -Depth 3

$MarkerPath = Join-Path $SourceRoot "runtime\.shared_runtime_ready.json"
$Marker | Set-Content -Path $MarkerPath -Encoding UTF8

Write-Host ""
Write-Host "============================================================"
Write-Host "  Setup complete!"
Write-Host "============================================================"
Write-Host ""
Write-Host "All packages are installed. Users can now launch instantly."
Write-Host "Release folder: $ReleaseDir"
Write-Host ""
