<#
.SYNOPSIS
    ONE-TIME admin setup for network drive deployments.

.DESCRIPTION
    Reads every app from apps/apps.json, collects all requirements.txt files,
    and installs every package directly into the bundled runtime's site-packages.
    After this runs once, ALL users get instant app launches -- no venv creation,
    no pip install, no waiting.

    Run this:
      - Once after placing the release folder on the network drive.
      - Again whenever you add a new app or bump a package version.

    Requires: write access to the runtime/ folder (admin or share owner only).

.PARAMETER ReleaseDir
    Path to the folder that contains runtime\ and apps\.
    Auto-detected: checks build\Unified-Streamlit-Launcher\ first, then the
    repo root itself (so you can run this directly from a repo on a network drive).

.EXAMPLE
    .\scripts\prepare_shared_runtime.ps1
    .\scripts\prepare_shared_runtime.ps1 -ReleaseDir "Z:\Vinay Vaida\Unified-Streamlit-Launcher"
#>

param(
    [string]$ReleaseDir = ""
)

$ErrorActionPreference = "Stop"

# ── Auto-detect the release / repo root ─────────────────────────────────────
if ($ReleaseDir -eq "") {
    $ScriptParent = Split-Path -Parent $PSScriptRoot

    # Option A: built release folder exists alongside repo
    $BuildRelease = Join-Path $ScriptParent "build\Unified-Streamlit-Launcher"
    if (Test-Path (Join-Path $BuildRelease "runtime\python.exe")) {
        $ReleaseDir = $BuildRelease
    }
    # Option B: running directly from the repo root (runtime\ is in the repo)
    elseif (Test-Path (Join-Path $ScriptParent "runtime\python.exe")) {
        $ReleaseDir = $ScriptParent
    }
    else {
        $ReleaseDir = $ScriptParent   # will fail below with a clear message
    }
}

$ReleaseDir = Resolve-Path $ReleaseDir

Write-Host ""
Write-Host "============================================================"
Write-Host "  Unified Streamlit Launcher -- Shared Runtime Setup"
Write-Host "============================================================"
Write-Host "Release folder : $ReleaseDir"

# ── Find the bundled Python ──────────────────────────────────────────────────
$Python = Join-Path $ReleaseDir "runtime\python.exe"
if (-not (Test-Path $Python)) {
    Write-Error @"
Bundled runtime not found at: $Python

Run scripts\fetch_runtime.ps1 first to download a portable Python runtime,
then re-run this script.
"@
    exit 1
}
Write-Host "Runtime python : $Python"
$PythonVersion = & $Python --version 2>&1
Write-Host "Python version : $PythonVersion"

# ── Read the app registry ────────────────────────────────────────────────────
$AppsJson = Join-Path $ReleaseDir "apps\apps.json"
if (-not (Test-Path $AppsJson)) {
    Write-Error "App registry not found: $AppsJson"
    exit 1
}
$Registry = Get-Content $AppsJson -Raw | ConvertFrom-Json

# ── Collect all requirements.txt files ──────────────────────────────────────
$AllRequirements = @()
$AllWheelhouses  = @()

foreach ($App in $Registry.applications) {
    if ($App.enabled -eq $false) { continue }

    $AppFolder = Join-Path $ReleaseDir "apps\$($App.folder)"
    $ReqFile   = Join-Path $AppFolder "requirements.txt"

    if (Test-Path $ReqFile) {
        $AllRequirements += $ReqFile
        Write-Host "  Found requirements: apps\$($App.folder)\requirements.txt"
    } else {
        Write-Host "  (no requirements.txt for $($App.name))"
    }

    $WheelDir = Join-Path $AppFolder "wheelhouse"
    if (Test-Path $WheelDir) {
        $AllWheelhouses += $WheelDir
    }
}

if ($AllRequirements.Count -eq 0) {
    Write-Host ""
    Write-Host "No requirements.txt files found -- nothing to install."
    exit 0
}

# ── Merge into a temp file ───────────────────────────────────────────────────
$TempReq = [System.IO.Path]::GetTempFileName() + ".txt"
$Lines   = @("# Auto-generated by prepare_shared_runtime.ps1")
foreach ($ReqFile in $AllRequirements) {
    $Lines += "# --- $ReqFile ---"
    $Lines += Get-Content $ReqFile
}
$Lines | Set-Content -Path $TempReq -Encoding UTF8
Write-Host ""
Write-Host "Merged $($AllRequirements.Count) requirements file(s)."

# ── Upgrade pip ──────────────────────────────────────────────────────────────
Write-Host "Upgrading pip..."
& $Python -m pip install --upgrade pip --quiet
if ($LASTEXITCODE -ne 0) { Write-Warning "pip upgrade failed (non-fatal, continuing)" }

# ── Install packages ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Installing all packages into shared runtime..."
Write-Host "(This may take a few minutes on first run.)"
Write-Host ""

$PipArgs = @("-m", "pip", "install", "--no-warn-script-location")

if ($AllWheelhouses.Count -gt 0) {
    Write-Host "Using offline wheelhouse(s) for faster install."
    $PipArgs += "--prefer-binary"
    foreach ($WheelDir in $AllWheelhouses) {
        $PipArgs += "--find-links"
        $PipArgs += $WheelDir
    }
}

$PipArgs += "-r"
$PipArgs += $TempReq

& $Python @PipArgs
$ExitCode = $LASTEXITCODE

Remove-Item $TempReq -Force -ErrorAction SilentlyContinue

if ($ExitCode -ne 0) {
    Write-Error "Package installation failed (exit code $ExitCode)."
    exit $ExitCode
}

# ── Verify ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Verifying Streamlit import..."
& $Python -c "import streamlit; print('  streamlit', streamlit.__version__, 'OK')"
if ($LASTEXITCODE -ne 0) {
    Write-Error "Streamlit import failed after installation."
    exit 1
}

# ── Write marker ─────────────────────────────────────────────────────────────
$Marker = @{
    prepared_at   = (Get-Date -Format "o")
    python        = $PythonVersion.ToString()
    release_dir   = $ReleaseDir.ToString()
    requirements  = $AllRequirements
} | ConvertTo-Json -Depth 3

$MarkerPath = Join-Path $ReleaseDir "runtime\.shared_runtime_ready.json"
$Marker | Set-Content -Path $MarkerPath -Encoding UTF8

Write-Host ""
Write-Host "============================================================"
Write-Host "  Setup complete!"
Write-Host "============================================================"
Write-Host ""
Write-Host "All packages are installed. Users can now launch instantly."
Write-Host "Release folder: $ReleaseDir"
Write-Host ""
